/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AuthForm: typeof import('./src/components/AuthForm.vue')['default']
    BaseCheckbox: typeof import('./src/components/BaseCheckbox.vue')['default']
    BaseDateInput: typeof import('./src/components/BaseDateInput.vue')['default']
    BaseExpandButton: typeof import('./src/components/BaseExpandButton.vue')['default']
    BaseInput: typeof import('./src/components/BaseInput.vue')['default']
    BaseLoadingSpinner: typeof import('./src/components/BaseLoadingSpinner.vue')['default']
    BaseSelect: typeof import('./src/components/BaseSelect.vue')['default']
    BaseToggle: typeof import('./src/components/BaseToggle.vue')['default']
    BaseTwoValSlider: typeof import('./src/components/BaseTwoValSlider.vue')['default']
    DataPaginator: typeof import('./src/components/DataPaginator.vue')['default']
    DataTableDays: typeof import('./src/components/DataTableDays.vue')['default']
    DataTableEntries: typeof import('./src/components/DataTableEntries.vue')['default']
    DataTableRow: typeof import('./src/components/DataTableRow.vue')['default']
    DataTableValues: typeof import('./src/components/DataTableValues.vue')['default']
    LatestEntriesDisplay: typeof import('./src/components/LatestEntriesDisplay.vue')['default']
    NavButton: typeof import('./src/components/NavButton.vue')['default']
    NotificationHandler: typeof import('./src/components/NotificationHandler.vue')['default']
    ReadingCard: typeof import('./src/components/ReadingCard.vue')['default']
    ReadingInputForm: typeof import('./src/components/ReadingInputForm.vue')['default']
    ReadingValuesCard: typeof import('./src/components/ReadingValuesCard.vue')['default']
    ReadingWeatherCard: typeof import('./src/components/ReadingWeatherCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SettingsFlag: typeof import('./src/components/SettingsFlag.vue')['default']
    SettingsSection: typeof import('./src/components/SettingsSection.vue')['default']
    SettingsSelectItem: typeof import('./src/components/SettingsSelectItem.vue')['default']
    StatsGraphs: typeof import('./src/components/StatsGraphs.vue')['default']
    TableDoubleHeader: typeof import('./src/components/TableDoubleHeader.vue')['default']
    TheDataPanel: typeof import('./src/components/TheDataPanel.vue')['default']
    TheLatestEntries: typeof import('./src/components/TheLatestEntries.vue')['default']
    TheNavFooter: typeof import('./src/components/TheNavFooter.vue')['default']
    TheNewEntry: typeof import('./src/components/TheNewEntry.vue')['default']
    TheSettings: typeof import('./src/components/TheSettings.vue')['default']
    TheStatsPanel: typeof import('./src/components/TheStatsPanel.vue')['default']
    TheTableFilter: typeof import('./src/components/TheTableFilter.vue')['default']
    TheTableTools: typeof import('./src/components/TheTableTools.vue')['default']
  }
}
